package edu.iacademy.cselec05.pm_rima;

import java.io.IOException;
import java.io.PrintWriter;
import java.lang.management.ManagementFactory;
import java.lang.management.RuntimeMXBean;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(name = "HelloServlet", urlPatterns = {"/hello"})
public class HelloServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        
        RuntimeMXBean rb = ManagementFactory.getRuntimeMXBean();
        String jvmName = rb.getVmName();
        String javaVersion = System.getProperty("java.version");
        String osName = System.getProperty("os.name");
        String tomcatVersion = getServletContext().getServerInfo();
        
        try {
            out.println("<!DOCTYPE html>");
            out.println("<html lang='en'>");
            out.println("<head>");
            out.println("    <meta charset='UTF-8'>");
            out.println("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
            out.println("    <title>System Status - Shopee Delivery Logistics</title>");
            out.println("    <link href='https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap' rel='stylesheet'>");
            out.println("    <style>");
            out.println("        :root {");
            out.println("            --bg-color: #0b0f19;");
            out.println("            --card-bg: rgba(255, 255, 255, 0.02);");
            out.println("            --card-border: rgba(255, 255, 255, 0.08);");
            out.println("            --primary-glow: linear-gradient(135deg, #f97316 0%, #ea580c 100%);");
            out.println("            --accent-glow: linear-gradient(135deg, #f97316 0%, #fdba74 100%);");
            out.println("            --text-primary: #f3f4f6;");
            out.println("            --text-secondary: #9ca3af;");
            out.println("            --text-accent: #fb923c;");
            out.println("            --success-color: #10b981;");
            out.println("        }");
            out.println("        * {");
            out.println("            box-sizing: border-box;");
            out.println("            margin: 0;");
            out.println("            padding: 0;");
            out.println("            font-family: 'Plus Jakarta Sans', sans-serif;");
            out.println("        }");
            out.println("        body {");
            out.println("            background-color: var(--bg-color);");
            out.println("            color: var(--text-primary);");
            out.println("            min-height: 100vh;");
            out.println("            display: flex;");
            out.println("            flex-direction: column;");
            out.println("            align-items: center;");
            out.println("            justify-content: center;");
            out.println("            overflow-x: hidden;");
            out.println("            position: relative;");
            out.println("        }");
            out.println("        body::before {");
            out.println("            content: '';");
            out.println("            position: absolute;");
            out.println("            width: 450px;");
            out.println("            height: 450px;");
            out.println("            background: radial-gradient(circle, rgba(249, 115, 22, 0.12) 0%, rgba(0,0,0,0) 70%);");
            out.println("            top: -100px;");
            out.println("            left: -100px;");
            out.println("            z-index: 0;");
            out.println("        }");
            out.println("        body::after {");
            out.println("            content: '';");
            out.println("            position: absolute;");
            out.println("            width: 500px;");
            out.println("            height: 500px;");
            out.println("            background: radial-gradient(circle, rgba(234, 88, 12, 0.08) 0%, rgba(0,0,0,0) 70%);");
            out.println("            bottom: -150px;");
            out.println("            right: -100px;");
            out.println("            z-index: 0;");
            out.println("        }");
            out.println("        .container {");
            out.println("            max-width: 800px;");
            out.println("            width: 90%;");
            out.println("            z-index: 10;");
            out.println("            padding: 40px 0;");
            out.println("        }");
            out.println("        .header {");
            out.println("            text-align: center;");
            out.println("            margin-bottom: 40px;");
            out.println("        }");
            out.println("        .header h1 {");
            out.println("            font-size: 2.5rem;");
            out.println("            font-weight: 700;");
            out.println("            background: linear-gradient(135deg, #ffffff 40%, #fdba74 100%);");
            out.println("            -webkit-background-clip: text;");
            out.println("            -webkit-text-fill-color: transparent;");
            out.println("            letter-spacing: -0.025em;");
            out.println("            margin-bottom: 10px;");
            out.println("        }");
            out.println("        .header p {");
            out.println("            color: var(--text-secondary);");
            out.println("            font-size: 1.1rem;");
            out.println("        }");
            out.println("        .glass-card {");
            out.println("            background: var(--card-bg);");
            out.println("            backdrop-filter: blur(16px);");
            out.println("            -webkit-backdrop-filter: blur(16px);");
            out.println("            border: 1px solid var(--card-border);");
            out.println("            border-radius: 24px;");
            out.println("            padding: 32px;");
            out.println("            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);");
            out.println("            margin-bottom: 24px;");
            out.println("        }");
            out.println("        .status-badge {");
            out.println("            display: inline-flex;");
            out.println("            align-items: center;");
            out.println("            gap: 8px;");
            out.println("            background: rgba(16, 185, 129, 0.1);");
            out.println("            border: 1px solid rgba(16, 185, 129, 0.2);");
            out.println("            color: var(--success-color);");
            out.println("            padding: 6px 14px;");
            out.println("            border-radius: 9999px;");
            out.println("            font-size: 0.85rem;");
            out.println("            font-weight: 600;");
            out.println("            margin-bottom: 20px;");
            out.println("        }");
            out.println("        .status-dot {");
            out.println("            width: 8px;");
            out.println("            height: 8px;");
            out.println("            background-color: var(--success-color);");
            out.println("            border-radius: 50%;");
            out.println("            box-shadow: 0 0 10px var(--success-color);");
            out.println("        }");
            out.println("        .grid {");
            out.println("            display: grid;");
            out.println("            grid-template-columns: repeat(2, 1fr);");
            out.println("            gap: 20px;");
            out.println("            margin-top: 24px;");
            out.println("        }");
            out.println("        @media (max-width: 600px) {");
            out.println("            .grid { grid-template-columns: 1fr; }");
            out.println("        }");
            out.println("        .info-item {");
            out.println("            background: rgba(255, 255, 255, 0.015);");
            out.println("            border: 1px solid rgba(255, 255, 255, 0.04);");
            out.println("            border-radius: 16px;");
            out.println("            padding: 20px;");
            out.println("            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);");
            out.println("        }");
            out.println("        .info-item:hover {");
            out.println("            transform: translateY(-2px);");
            out.println("            border-color: rgba(249, 115, 22, 0.2);");
            out.println("            background: rgba(255, 255, 255, 0.03);");
            out.println("        }");
            out.println("        .info-label {");
            out.println("            font-size: 0.85rem;");
            out.println("            color: var(--text-secondary);");
            out.println("            text-transform: uppercase;");
            out.println("            letter-spacing: 0.05em;");
            out.println("            margin-bottom: 6px;");
            out.println("        }");
            out.println("        .info-value {");
            out.println("            font-size: 1.1rem;");
            out.println("            font-weight: 600;");
            out.println("            color: var(--text-primary);");
            out.println("        }");
            out.println("        .accent-text {");
            out.println("            color: var(--text-accent);");
            out.println("        }");
            out.println("        .back-btn {");
            out.println("            display: block;");
            out.println("            text-align: center;");
            out.println("            margin-top: 24px;");
            out.println("            color: var(--text-accent);");
            out.println("            text-decoration: none;");
            out.println("            font-size: 0.95rem;");
            out.println("            font-weight: 600;");
            out.println("            transition: color 0.2s;");
            out.println("        }");
            out.println("        .back-btn:hover {");
            out.println("            color: #fdba74;");
            out.println("        }");
            out.println("        footer {");
            out.println("            margin-top: 40px;");
            out.println("            text-align: center;");
            out.println("            font-size: 0.8rem;");
            out.println("            color: #4b5563;");
            out.println("        }");
            out.println("    </style>");
            out.println("</head>");
            out.println("<body>");
            out.println("    <div class='container'>");
            out.println("        <div class='header'>");
            out.println("            <h1>Shopee Delivery Diagnostics</h1>");
            out.println("            <p>Servlet dynamically rendered environment context</p>");
            out.println("        </div>");
            out.println("        <div class='glass-card'>");
            out.println("            <div class='status-badge'>");
            out.println("                <div class='status-dot'></div>");
            out.println("                <span>Tomcat &amp; MySQL Engine Active</span>");
            out.println("            </div>");
            out.println("            <h2 style='font-weight: 600; font-size: 1.35rem; margin-bottom: 10px; color: var(--text-accent);'>System Runtime Properties</h2>");
            out.println("            <p style='color: var(--text-secondary); font-size: 0.95rem;'>Live diagnostic metrics fetched directly from JVM and Web Container context.</p>");
            out.println("            <div class='grid'>");
            out.println("                <div class='info-item'>");
            out.println("                    <div class='info-label'>Java Version</div>");
            out.println("                    <div class='info-value accent-text'>" + javaVersion + "</div>");
            out.println("                </div>");
            out.println("                <div class='info-item'>");
            out.println("                    <div class='info-label'>Web Server</div>");
            out.println("                    <div class='info-value'>" + tomcatVersion + "</div>");
            out.println("                </div>");
            out.println("                <div class='info-item'>");
            out.println("                    <div class='info-label'>Operating System</div>");
            out.println("                    <div class='info-value'>" + osName + "</div>");
            out.println("                </div>");
            out.println("                <div class='info-item'>");
            out.println("                    <div class='info-label'>JVM VM Name</div>");
            out.println("                    <div class='info-value' style='font-size: 0.9rem;'>" + jvmName + "</div>");
            out.println("                </div>");
            out.println("                <div class='info-item'>");
            out.println("                    <div class='info-label'>Client IP Address</div>");
            out.println("                    <div class='info-value accent-text'>" + request.getRemoteAddr() + "</div>");
            out.println("                </div>");
            out.println("                <div class='info-item'>");
            out.println("                    <div class='info-label'>Context Path</div>");
            out.println("                    <div class='info-value'><code>" + request.getContextPath() + "</code></div>");
            out.println("                </div>");
            out.println("            </div>");
            out.println("        </div>");
            out.println("        <a href='" + request.getContextPath() + "/' class='back-btn'>&larr; Back to Logistics Dashboard</a>");
            out.println("    </div>");
            out.println("    <footer>");
            out.println("        Shopee Delivery System v1.0 &bull; edu.iacademy.cselec05.pm_rima");
            out.println("    </footer>");
            out.println("</body>");
            out.println("</html>");
        } finally {
            out.close();
        }
    }
}
